---
- name: Configure AWS CLI with access keys
  command: aws configure
  environment:
   AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
   AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
   AWS_DEFAULT_REGION: "{{ aws_region }}"
  when: aws_access_key_id is defined and aws_secret_access_key is defined



# aws_configure_role/tasks/configure_aws.yml

# - name: Configure AWS CLI aws_access_key_id
#   command: aws configure set aws_access_key_id {{ aws_access_key_id }}
#   when: aws_access_key_id is defined and aws_secret_access_key is defined
#   register: aws_cli_configure_access_key
#   changed_when: false

# - name: Configure AWS CLI aws_secret_access_key
#   command: aws configure set aws_secret_access_key {{ aws_secret_access_key }}
#   when: aws_access_key_id is defined and aws_secret_access_key is defined
#   register: aws_cli_configure_secret_key
#   changed_when: false

# - name: Configure AWS CLI default region
#   command: aws configure set default.region {{ aws_region }}
#   when: aws_access_key_id is defined and aws_secret_access_key is defined
#   register: aws_cli_configure_region
#   changed_when: false

# - name: Display AWS CLI configuration outputs
#   debug:
#     msg: |
#       Access Key Configure Output: {{ aws_cli_configure_access_key.stdout }}
#       Secret Key Configure Output: {{ aws_cli_configure_secret_key.stdout }}
#       Region Configure Output: {{ aws_cli_configure_region.stdout }}
#   when: aws_access_key_id is defined and aws_secret_access_key is defined



#######
- name: Update kubeconfig for EKS cluster
  command: eksctl create cluster --name "{{ cluster_name }}" --region "{{ aws_region }}" --nodes 2 --node-type t2.micro --managed

  when:
    - aws_region is defined
    - cluster_name is defined
